[tool.poetry]
name = "tweakers"
version = "0.3.2"
description = "A Python wrapper for tweakers.net"
authors = ["Timo"]
license = "MIT"

readme = "README.md"

repository = "https://github.com/timotk/tweakers"

classifiers=[
    "Programming Language :: Python :: 3.6",
    "Programming Language :: Python :: 3.7",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent"
]

[tool.poetry.dependencies]
python = ">=3.6"
requests-html = "^0.10.0"
dateparser = "^0.7.0"

[tool.poetry.dev-dependencies]
pytest = "^4.0"
pytest-cov = "^2.6"
black = "^19.10b0"
